
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # mount code for live changes (optional)
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # mount code
    depends_on:
      - backend